title: 'Karan Sodhi'
description: 'Junior at the University of Illinois at Urbana-Champaign (UIUC). <br /> Majoring in Computer Science.  <br /> Email: me@karansodhi.com'
logo: /assets/img/logotiny.jpg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
